### ISSUE TITLE
docs.rs repo link broken

### ISSUE THREAD

**Issue by spookyvision** [DioxusLabs/sdk#43]
on [docs.rs](https://docs.rs/dioxus-sdk/latest/dioxus_sdk/index.html) the "repository" link points at https://github.com/DioxusLabs/dioxus-sdk/ which 404s; it should be https://github.com/DioxusLabs/sdk/

**Comment by marc2332** [comment]
Ooops!

**Comment by marc2332** [comment]
Looks like it's already fixed on git, it should be ✅ in the next release :)

**Comment by DogeDark** [comment]
Fixed!
