### ISSUE TITLE
Regression: use_window_resize() does not update or panics on resize

### ISSUE THREAD

**Issue by bcorey** [DioxusLabs/sdk#48]
if several components use the `use_window_size()` hook, they no panic or don't update when the window is resized.

paste the below into the 'dx new' default project to test.
```
// none of the values update on resize
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", features = ["window_size"] }

```

```

#[component]
fn App() -> Element {

    rsx! {
        WindowSizeRenderer {}
        WindowSizeRenderer {}
        WindowSizeRenderer {}
        WindowSizeRenderer {}
    }
}

#[component]
fn WindowSizeRenderer() -> Element {
    let window = use_window_size();
    let width = window().width;
    rsx! {
        div {
            style: "width: 100px; height: 30px; text-align: center;",
            "{width}"
        }
    }
}

```

**Comment by bcorey** [comment]
this does not occur on my local copy of the repo before commit `2fbad1bfffa1007756b8ecfa3901ecdd0ec1890d`

**Comment by DogeDark** [comment]
I am not able to reproduce this issue on either Web or Desktop. What platform are you targeting and what operating system do you use? Also, to confirm, are you testing it by resizing the window width and not the window height? 

It's odd as `2fbad1b` was meant to fix a similar issue. Originally, `use_window_size()` could only be used once.

**Comment by bcorey** [comment]
I'm on macos and I'm seeing the issue in firefox, brave, and safari. resizing in either direction causes it.

**Comment by bcorey** [comment]
this is odd: it's now working for me accessing the git repo directly but the cloned up to date copy fails to update any of the values on resize.

```
# up to date with origin/master after git fetch -ft git pull
# none of the values update
dioxus-sdk = { path = "../sdk/sdk", features = ["window_size"]}

# BUT using this instead now works
dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", features = ["window_size"]}
```

**Comment by bcorey** [comment]
after running `cargo clean` & `dx serve` the local version of the repo works as well

**Comment by bcorey** [comment]
closing since it seems like this was due to build artifacts from switching repo versions
