### ISSUE TITLE
Adding Apache 2.0 License to SDK

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/sdk#63]
To follow the standard practice of dual-licensing Rust crates (and most Dioxus projects) as MIT and Apache 2.0, I would like to add the Apache 2.0 license to SDK. In order to do this, we need approval from every existing contributor:

- [x] @DogeDark 
- [x] @marc2332 
- [x] @ealmloff 
- [x] @striezel 
- [x] @samtay 
- [x] @esimkowitz 

I would greatly appreciate it if you could comment below stating that you agree (or if you disagree) to relicense your contributions under Apache 2.0 and the existing MIT license.

**Comment by esimkowitz** [comment]
Agreed

**Comment by marc2332** [comment]
SGTM

**Comment by ealmloff** [comment]
Agreed

**Comment by striezel** [comment]
I agree to relicense my contributions to this repository under Apache 2.0 and the existing MIT license. :)

**Comment by DogeDark** [comment]
Thank you, everyone!
