### ISSUE TITLE
Rust analyser can't make sense of sdk

### ISSUE THREAD

**Issue by alper** [DioxusLabs/sdk#64]
https://github.com/user-attachments/assets/a0e5a9d3-c1ba-4a5f-b5cc-81940c17e9ac

I'm not sure why this is the case but I can click into Dioxus methods, but not into sdk methods. Hovering over sdk types also gives `{unknown}`.

**Comment by marc2332** [comment]
Perhaps you need to tell RA to use wasm?

**Comment by marc2332** [comment]
I mean something like this: https://github.com/DioxusLabs/sdk/blob/765dcfe237945fa76344c48a385d8c85b17a7881/.vscode/settings.json#L5

**Comment by marc2332** [comment]
> And that works… But isn't it weird that it would work for dioxus main but not the sdk at first?
Glad that worked

It it is not weird as when you use dioxus, you are not interacting with any wasm-specific API (most of the time), in the other hand all the geolocation APIs from the sdk are only available for wasm targets, for which RA needs to be configured to understand

**Comment by alper** [comment]
That makes sense but it seems like setting it this way works for both for some reason.

**Comment by marc2332** [comment]
> Ah, I guess because both can be compiled to wasm but not both can be compiled to arm…?

correct :)

**Comment by DogeDark** [comment]
> all the geolocation APIs from the sdk are only available for wasm targets, 

And windows!

**Comment by marc2332** [comment]
Closing this then :)

**Comment by jkelleyrtp** [comment]
Would it make sense to keep all APIs available on all platforms but do nothing on unsupported platforms?

**Comment by alper** [comment]
I had already had to explicitly add this to `bacon.toml` but hadn't considered that `rust-analyser` would also need this.

Maybe I can add a tooling bit to the docs?

**Comment by marc2332** [comment]
> Would it make sense to keep all APIs available on all platforms but do nothing on unsupported platforms?

How do you deal with returned values?

**Comment by DogeDark** [comment]
> How do you deal with returned values?

I imagine any API we provide will be fallible and we could return a NotSupported error. Alternatively we could provide a fallback function that is marked deprecated that panics when used on an unsupported platform while still providing the type information.
